//midpoint circle
#include<graphics.h>
#include<conio.h>
#include<stdio.h>
void main(){
	int x,y,x_mid,y_mid,radius,pk;
	int g_mode,g_driver=DETECT;
	clrscr();
	initgraph(&g_driver,&g_mode,"C:\\TURBOC3\\BGI");
	printf("Enter the coordinates: \n");
	scanf("%d %d",&x_mid,&y_mid);
	printf("Enter the radius= \n");
	scanf("%d",&radius);
	x=0;
	y=radius;
	pk=1-radius;
	do{
		putpixel(x_mid+x, y_mid+y, YELLOW);
		putpixel(x_mid+y, y_mid+x, YELLOW);
		putpixel(x_mid-y, y_mid+x, YELLOW);
		putpixel(x_mid-x, y_mid+y, YELLOW);
		putpixel(x_mid-x, y_mid-y, YELLOW);
		putpixel(x_mid-y, y_mid-x, YELLOW);
		putpixel(x_mid+y, y_mid-x, YELLOW);
		putpixel(x_mid+x, y_mid-y, YELLOW);
		if(pk<0){
			pk=pk+(2*x)+1;
		}
		else{
			y=y-1;
			pk=pk+(2*x)-(2*y)+1;
		}
		x=x+1;
	}
	while(y>x);
	getch();
}